/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import vacc.*;
import com.itextpdf.text.Document;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import java.io.PrintWriter;

/**
 *
 * @author abudo
 */
public class make_invoice extends javax.swing.JInternalFrame {

    /**
     * Creates new form make_invoice
     */
   
         timeslot t=new timeslot();
         vacc_center v=new vacc_center();
         admin ad=new admin();
         exceptionrule ex=new exceptionrule();
         timeslotinternalF ti=new  timeslotinternalF();
                     int count=0;
    public make_invoice() {
        initComponents();
         DefaultComboBoxModel dm= new DefaultComboBoxModel(t.day);
         jComboBoxday.setModel(dm);
         String[] hour={"1","2","3","4"};
          DefaultComboBoxModel d=new  DefaultComboBoxModel(hour);
          jComboBoxhour.setModel(d);
           DefaultComboBoxModel dd=new  DefaultComboBoxModel(v.drugs);
              jComboBoxdrug.setModel(dd);
              String[] payment={"cash","visa"};
              DefaultComboBoxModel ddd=new  DefaultComboBoxModel(payment);
              jComboBoxpayment.setModel(ddd);  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxdrug = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxday = new javax.swing.JComboBox<>();
        jComboBoxhour = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxpayment = new javax.swing.JComboBox<>();
        jLabelSucessOrFail = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setClosable(true);

        jLabel1.setText("Drug");

        jComboBoxdrug.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Day");

        jComboBoxday.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxhour.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("hour");

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Payment type");

        jComboBoxpayment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(63, 63, 63))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5)
                                .addGap(21, 21, 21)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1)
                            .addComponent(jComboBoxhour, 0, 196, Short.MAX_VALUE)
                            .addComponent(jComboBoxdrug, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxday, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxpayment, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabelSucessOrFail, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxdrug, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxhour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxpayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jLabelSucessOrFail, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:        
        try{
           // int check=0;
           double cost=0.0;
            int i=0,q=0; 
            int hour=0;
            String day="";
            client x = new client();
            x.loadFromFile();
           while(i<x.clients.size())
            {
               if(x.clients.get(i).drug==null)
               {                 
                          
                 for(int j=0;j<v.drugs.length;j++){
                   if (v.drugs[j]==jComboBoxdrug.getSelectedItem()) {
                     day=v.drugs[j];
               }
                 }
                 for(int j=0;j<v.stock_quantity.length;j++)
                 {
                     if(v.drugs[j]==day){
                         cost=v.piece_drugcost[j];
                          count= j;
                         // JOptionPane.showMessageDialog(null, v.stock_quantity[j]);
                     update_quantity();
                     }
                     
                 }
                        x.clients.get(i).drug=day;
                     for(int m=0;m<t.day.length;m++){
                      if (t.day[m]==jComboBoxday.getSelectedItem()) {
                        day=t.day[m];
                        q++;
                }
                     }
                     if(q==4)
                         ex.check_d(t, day);
                    x.clients.get(i).day=day;
                     for(int y=0;y<t.day.length;y++)
                        {
                             if(t.day[y]==x.clients.get(i).day)
                             {
                                  hour=y*4;
                             }
                        }
                     
                  if (jComboBoxhour.getSelectedItem().equals("1")) {
                  hour=hour+1;
                  } else if (jComboBoxhour.getSelectedItem().equals("2")) {
                  hour=hour+2;
                  } else if (jComboBoxhour.getSelectedItem().equals("3")) {
                  hour=hour+3;
                  } else if (jComboBoxhour.getSelectedItem().equals("4")) {
                  hour=hour+4;
                 }
                  int u;
                  for( u=0;u<t.orderedh.length;u++)
                  {
                      if(t.orderedh[u]==hour)
                           hour=ex.check_h(t, hour);
                  }
                 x.clients.get(i).hour=hour;  
                  
                 /* if(t.check_validtime(hour)){
                      check++;
                       JOptionPane.showMessageDialog(null," found ");
                  }*/
                 /* if(check==1){
                    ex.check_t(hour,t,x.clients.get(i).day);
                  }*/
                                          
                      if (jComboBoxpayment.getSelectedItem().equals("cash")) {
                        x.clients.get(i).payment_type="cash";
                     } else if (jComboBoxpayment.getSelectedItem().equals("visa")) {
                       x.clients.get(i).payment_type="visa";
                     long s;
                     s=ex.checkvisanumber();
                         x.clients.get(i).set_nvisa(s); 
                     }                  
                      //if(check==0){
                            x.commitToFile();
                            
                jLabelSucessOrFail.setText("client:"+x.clients.get(i).get_id()+",Added Successfully ... !");
                 Document document=new Document(); 
                 PdfWriter.getInstance(document,new FileOutputStream("invoice.pdf")); 
                 document.open(); document.add(new Paragraph(x.clients.get(i).toString()+"\ncost:"+cost+" dollar\nthanks,:)")); 
                 document.close();
               
                resetPanelData();  
               // check=0;
                   //   }
               }
             else {
                jLabelSucessOrFail.setText("Failed to insert ... !");
               }
               i++;
        } 
    }
        catch(Exception e){
             JOptionPane.showMessageDialog(null,e+" in make_invoice");
        }
    }
    public void update_quantity()
    {
        try{
            
            PrintWriter p=new PrintWriter(ti.f);
            for(int i=0;i<v.stock_quantity.length;i++)
                if(i==count)
                p.println(v.stock_quantity[i]-1);
            else
                    p.println(v.stock_quantity[i]);
             p.close();
        }
        catch(Exception e){
             JOptionPane.showMessageDialog(null,e+" in update_quantity");
        }
    }

        protected void resetPanelData() {
       jComboBoxdrug.setSelectedIndex(0);
        jComboBoxday.setSelectedIndex(0);
          jComboBoxhour.setSelectedIndex(0);
          jComboBoxpayment.setSelectedIndex(0);

           
    }//GEN-LAST:event_jButton1ActionPerformed

/**/ 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBoxday;
    private javax.swing.JComboBox<String> jComboBoxdrug;
    private javax.swing.JComboBox<String> jComboBoxhour;
    private javax.swing.JComboBox<String> jComboBoxpayment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelSucessOrFail;
    // End of variables declaration//GEN-END:variables
}
