/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import java.io.*;
import java.util.Scanner;
import javax.swing.JOptionPane;
import vacc.*;


/**
 *
 * @author abudo
 */
public class timeslotinternalF extends javax.swing.JInternalFrame {

    /**
     * Creates new form timeslotinternalF
     */
    File f=new File("vaccq.txt");
      timeslot t=new timeslot();
    client c=new client();
    vacc_center v=new vacc_center();
    public timeslotinternalF() {
        initComponents();       
         set_time();
        show_time(); 
         set_costs();
        // update_quantity();
         show_quantity();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreatime = new javax.swing.JTextArea();

        setClosable(true);
        setTitle("time");

        jTextAreatime.setEditable(false);
        jTextAreatime.setColumns(20);
        jTextAreatime.setRows(5);
        jScrollPane1.setViewportView(jTextAreatime);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void show_time()
    {      
        try{
       // int m=0;
     jTextAreatime.append("we work all days from 1pm:4pm\n");
        jTextAreatime.append("that's ordered time:\n");
    /*  for(int i=0;i<t.day.length;i++)
       {
           for(int j=0;j<t.orderedd.length;j++)
           {
               if(t.day[i]==t.orderedd[j]&&m==0)
               {
                    jTextAreatime.append(t.day[i]+"  ");
                   m++;
               }              
           }
           m=0;          
       }
        jTextAreatime.append("\n");     */
       int u=0;
     
       while(u<25){ 
      for(int j=0;j<t.day.length;j++)
       {
            jTextAreatime.append(t.day[j]+":");
       for(int i=0;i<t.orderedh.length;i++)
       {
           if(t.orderedh[i]==u+1)
           {
               jTextAreatime.append("1,");
           }
           if(t.orderedh[i]==u+2)
           {
               jTextAreatime.append("2,");
           }
           if(t.orderedh[i]==u+3)
           {
                jTextAreatime.append("3,");
           }
           if(t.orderedh[i]==u+4)
           {
                jTextAreatime.append("4,");
           }
       }
      
        jTextAreatime.append("--\n");       
       u+=4;     
      
       }
        }
           jTextAreatime.append("\n");
        }
         catch(Exception e){
             JOptionPane.showMessageDialog(null,e+" in show_time");
        }
}
    public void set_time()
    {
        try{
       c.loadFromFile();
        for(int i=0;i<c.clients.size();i++)
        {
             t.orderedd[i]=c.clients.get(i).day;
           t.orderedh[i]=c.clients.get(i).hour;          
        }
        }
         catch(Exception e){
             JOptionPane.showMessageDialog(null,e+" in set_time");
        }
    }
    public void set_costs()
    {
        jTextAreatime.append("--------------------------\n");
        jTextAreatime.append("drugs and their costs:\n");
        for(int i=0;i<v.drugs.length;i++)
        {
             jTextAreatime.append(v.drugs[i]+":");
              jTextAreatime.append(v.piece_drugcost[i]+"\n");
        }
    }
    
     public void show_quantity()
    {
        try{
            jTextAreatime.append("--------------------------\n");
             jTextAreatime.append("drugs quantity:\n");
            int i=0;
             Scanner s=new Scanner(f);
             while(s.hasNextInt())
             {
                 v.stock_quantity[i]=s.nextInt();
                  jTextAreatime.append(v.drugs[i]+":");
                  jTextAreatime.append(v.stock_quantity[i]+"\n");
                  i++;
             }
             s.close();
        }
         catch(Exception e){
        JOptionPane.showMessageDialog(null,e+" in show_quantity");
         }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreatime;
    // End of variables declaration//GEN-END:variables
}
