/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;
import vacc.*;

/**
 *
 * @author abudo
 */
public class timeslotFrame extends javax.swing.JFrame {

    /**
     * Creates new form timeslotFrame
     */
      
    timeslot t=new timeslot();
    client c=new client();
    public timeslotFrame() {
        initComponents();              
       set_time();
       show_time();      
       this.setTitle("time");         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreatime = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextAreatime.setEditable(false);
        jTextAreatime.setColumns(20);
        jTextAreatime.setRows(5);
        jScrollPane1.setViewportView(jTextAreatime);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(timeslotFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(timeslotFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(timeslotFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(timeslotFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new timeslotFrame().setVisible(true);
            }
        });
    }
    public void show_time()
    {      
        int m=0;
     jTextAreatime.append("we work all days from 1pm:4pm\n");
        jTextAreatime.append("that's ordered time:\n");
       for(int i=0;i<t.day.length;i++)
       {
           for(int j=0;j<t.orderedd.length;j++)
           {
               if(t.day[i]==t.orderedd[j]&&m==0)
               {
                    jTextAreatime.append(t.day[i]+"  ");
                   m++;
               }              
           }
           m=0;          
       }
        jTextAreatime.append("\n");      
       int u=0;
     
          while(u<25){
       for(int i=0;i<t.orderedh.length;i++)
       {
           if(t.orderedh[i]==u+1)
           {
               jTextAreatime.append("1,");
           }
           if(t.orderedh[i]==u+2)
           {
               jTextAreatime.append("2,");
           }
           if(t.orderedh[i]==u+3)
           {
                jTextAreatime.append("3,");
           }
           if(t.orderedh[i]==u+4)
           {
                jTextAreatime.append("4,");
           }
       }
      
        jTextAreatime.append("--");       
       u+=4;     
      }
           jTextAreatime.append("\n");
}
    public void set_time()
    {
        for(int i=0;i<c.clients.size();i++)
        {
           t.orderedh[i]=c.clients.get(i).hour;
           t.orderedd[i]=c.clients.get(i).day;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreatime;
    // End of variables declaration//GEN-END:variables
}
