/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Framespanels;

import vacc.*;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;


/**
 *
 * @author abudo
 */
public class client_Updatepanel extends javax.swing.JPanel {

    /**
     * Creates new form client_Updatepanel
     */
         timeslot t=new timeslot();
         vacc_center v=new vacc_center();
         admin ad=new admin();
         exceptionrule ex=new exceptionrule();
         String payment;
         double ev;
    public client_Updatepanel() {
        initComponents();       
        jTextFieldid.setEditable(false);
          DefaultComboBoxModel dm= new DefaultComboBoxModel(t.day);
         jComboBoxday.setModel(dm);
         String[] hour={"1","2","3","4"};
          DefaultComboBoxModel d=new  DefaultComboBoxModel(hour);
          jComboBoxhour.setModel(d);
           DefaultComboBoxModel dd=new  DefaultComboBoxModel(v.drugs);
              jComboBoxdrug.setModel(dd);               
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField7 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButtonupdate = new javax.swing.JButton();
        jButtondelete = new javax.swing.JButton();
        jTextFieldlname = new javax.swing.JTextField();
        jTextFieldid = new javax.swing.JTextField();
        jTextFieldfname = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxdrug = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldemail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxday = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxhour = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabelage = new javax.swing.JLabel();
        jTextFieldage = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabelSucessOrFail = new javax.swing.JLabel();

        jTextField7.setText("jTextField7");

        jButton1.setText("search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonupdate.setText("Update");
        jButtonupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonupdateActionPerformed(evt);
            }
        });

        jButtondelete.setText("Delete");
        jButtondelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtondeleteActionPerformed(evt);
            }
        });

        jTextFieldid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldidActionPerformed(evt);
            }
        });

        jLabel1.setText("First name");

        jLabel2.setText("Last name");

        jLabel3.setText("ID");

        jLabel4.setText("drug");

        jComboBoxdrug.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Email");

        jLabel6.setText("Day");

        jComboBoxday.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setText("hour");

        jComboBoxhour.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabelage.setText("Age");

        jTextFieldage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8))
                                .addGap(468, 468, 468))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(89, 89, 89)))
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtondelete)
                            .addComponent(jButtonupdate))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabelage)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(39, 39, 39)
                                        .addComponent(jLabel7))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))))
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxdrug, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxhour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldfname, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldlname, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldemail, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldage, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxday, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldid, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jLabelSucessOrFail, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldfname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldlname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jButtonupdate))
                        .addGap(16, 16, 16)
                        .addComponent(jLabel4)
                        .addGap(13, 13, 13)
                        .addComponent(jButtondelete))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jTextFieldid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxdrug, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelage)
                            .addComponent(jTextFieldage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jComboBoxday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jComboBoxhour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabelSucessOrFail, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
         try{
        if (!jTextField1.getText().equals("")) {
            client x = new client();
         
            client returned = x.searchclienttById(Integer.parseInt(jTextField1.getText()));
             set_ev(returned.get_evnumber());
             set_payment(returned.payment_type);
            if (returned.get_id() >= 0) {          
                setPanelData(returned);
            } else {
                jLabelSucessOrFail.setText("Not Found ...!");
            }
        } else {
            jLabelSucessOrFail.setText("Missing required Fields ... !  Please, Search By ID before submit ...!");
        }
         }
         catch(Exception e){
             JOptionPane.showMessageDialog(null,e+" in search");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtondeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtondeleteActionPerformed
        // TODO add your handling code here:
        try{
         if (!jTextField1.getText().equals("")) {
            client x = new client();
            if (ad.delete(Integer.parseInt(jTextField1.getText()))) {
                jLabelSucessOrFail.setText("Deleted Successfully ... !");
                resetPanelData();
            } else {
                jLabelSucessOrFail.setText("Failed to delete ... !");
            }
        } else {
            jLabelSucessOrFail.setText("Missing required Fields ... !  Please, Search By ID before submit ...!");
        }
        }
        catch(Exception e){
             JOptionPane.showMessageDialog(null,e+" in delete");
        }
    }//GEN-LAST:event_jButtondeleteActionPerformed

    private void jButtonupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonupdateActionPerformed
        // TODO add your handling code here:
        try{
         if (!jTextFieldid.getText().equals("") && !jTextFieldfname.getText().equals("") && !jTextFieldlname.getText().equals("") && !jTextFieldemail.getText().equals("") && !jTextFieldage.getText().equals("") ) {
            String email;
            int age;
            
            client x = new client();       
             x.set_id(Integer.parseInt(jTextFieldid.getText()));           
            x.set_fname(jTextFieldfname.getText());
            x.set_lname(jTextFieldlname.getText());
           // x.set_email(jTextFieldemail.getText());   
           x.payment_type=get_payment();
           x.set_evnumber(get_ev());
           email=jTextFieldemail.getText();
            if(email.contains("@")&& email.contains(".")){
                x.set_email(email);
            }
            else{
               email=ex.checkEmail("email");
            }
             x.set_email(email);
            //x.set_age(Integer.parseInt(jTextFieldage.getText()));
             age=Integer.parseInt(jTextFieldage.getText());
            if(age>0){
                x.set_age(age);
            }
            else{
               age=ex.checkPositive(" age ");
               x.set_age(age);
            }
              int hour=0;          
              for(int i=0;i<t.day.length;i++){
            if (t.day[i]==jComboBoxday.getSelectedItem()) {
                x.day=t.day[i];
                }
             }
                for(int y=0;y<t.day.length;y++)
                        {
                             if(t.day[y]==x.day)
                             {
                                  hour=y*4;
                             }
                         }
            if (jComboBoxhour.getSelectedItem().equals("1")) {
                x.hour=hour+1;
            } else if (jComboBoxhour.getSelectedItem().equals("2")) {
                x.hour=hour+2;
            } else if (jComboBoxhour.getSelectedItem().equals("3")) {
                x.hour=hour+3;
            } else if (jComboBoxhour.getSelectedItem().equals("4")) {
                x.hour=hour+4;
            }
            for(int i=0;i<v.drugs.length;i++){
            if (v.drugs[i]==jComboBoxdrug.getSelectedItem()) {
                x.drug=v.drugs[i];
               } 
             }
     
            if (ad.update(x)) {
                jLabelSucessOrFail.setText("Updated Successfully ... !");
                resetPanelData();
            } else {
                jLabelSucessOrFail.setText("Failed to Update ... !");
            }
        } else {
            jLabelSucessOrFail.setText("Missing required Fields ... ! ");
        }
        }
        catch(Exception e){
             JOptionPane.showMessageDialog(null,e+"in update");
        }
    }//GEN-LAST:event_jButtonupdateActionPerformed

    private void jTextFieldageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldageActionPerformed

    private void jTextFieldidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldidActionPerformed
 protected void resetPanelData() {
        jTextFieldfname.setText("");
        jTextFieldlname.setText("");
        jTextFieldid.setText("");
        jTextFieldemail.setText("");
         jTextFieldage.setText("");
        jComboBoxdrug.setSelectedIndex(0);
        jComboBoxday.setSelectedIndex(0);
          jComboBoxhour.setSelectedIndex(0);

    }

    protected void setPanelData(client x) {
        
        jTextFieldid.setText("" + x.get_id());
        jTextFieldfname.setText("" + x.get_fname());
        jTextFieldlname.setText("" + x.get_lname());
        jTextFieldemail.setText("" + x.get_email());       
        jTextFieldage.setText(""+x.get_age());
        for(int u=0;u<t.hours.length;u+=4){
        if (x.hour ==u+1) {
            jComboBoxhour.setSelectedIndex(0);
        } else if (x.hour ==u+2) {
            jComboBoxhour.setSelectedIndex(1);
        } else if (x.hour ==u+3) {
            jComboBoxhour.setSelectedIndex(2);
        } else if (x.hour ==u+4) {
            jComboBoxhour.setSelectedIndex(3);
        }
        }
        for(int j=0;j<v.drugs.length;j++)
        {
            if(v.drugs[j].equals(x.drug))
                jComboBoxdrug.setSelectedIndex(j);
        }

        if (x.day.equals("saturday")) {
            jComboBoxday.setSelectedIndex(0);
        } else if (x.day.equals("sunday")) {
            jComboBoxday.setSelectedIndex(1);
        } else if (x.day.equals("moday")) {
            jComboBoxday.setSelectedIndex(2);
        } else if (x.day.equals("tuesday")) {
            jComboBoxday.setSelectedIndex(3);
        } else if (x.day.equals("wednesday")) {
            jComboBoxday.setSelectedIndex(4);
        }
        else if (x.day.equals("thursday")) {
            jComboBoxday.setSelectedIndex(5);
        }
        else if (x.day.equals("friday")) {
            jComboBoxday.setSelectedIndex(6);
        }
        x.commitToFile();                           
    }
    protected void set_payment(String x)
    {
        this.payment=x;
    }
    protected String get_payment()
    {
        return this.payment;
    }
     protected void set_ev(double x)
     {
         this.ev=x;
    }
     protected double get_ev()
    {
      return this.ev;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtondelete;
    private javax.swing.JButton jButtonupdate;
    private javax.swing.JComboBox<String> jComboBoxday;
    private javax.swing.JComboBox<String> jComboBoxdrug;
    private javax.swing.JComboBox<String> jComboBoxhour;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelSucessOrFail;
    private javax.swing.JLabel jLabelage;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextFieldage;
    private javax.swing.JTextField jTextFieldemail;
    private javax.swing.JTextField jTextFieldfname;
    private javax.swing.JTextField jTextFieldid;
    private javax.swing.JTextField jTextFieldlname;
    // End of variables declaration//GEN-END:variables

}
