/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Framespanels;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import vacc.*;

/**
 *
 * @author abudo
 */
public class client_Listpanel extends javax.swing.JPanel {

    /**
     * Creates new form client_Listpanel
     */
    admin ad=new admin();
    timeslot t=new timeslot();
    public client_Listpanel() {
        initComponents();
       addRowsTojTable();
    }
    
    public void addRowsTojTable() {
        try{
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        Object rowData[] = new Object[10];

        client c = new client();       
        ArrayList<client> clients = new ArrayList<client>();

        clients = ad.list(c);           
        for (client x : clients) {
            rowData[0] = x.get_id();
            rowData[1] = x.get_fname();
            rowData[2] = x.get_lname();                  
            rowData[3] = x.get_age();
            rowData[4] = x.drug;  
            rowData[5] = x.day;         
           if(x.hour==1||x.hour==5||x.hour==9||x.hour==13||x.hour==17||x.hour==21||x.hour==25)
           {
               rowData[6]=1;
           }
           if(x.hour==2||x.hour==6||x.hour==10||x.hour==14||x.hour==18||x.hour==22||x.hour==26)
           {
               rowData[6]=2;
           }
           if(x.hour==3||x.hour==7||x.hour==11||x.hour==15||x.hour==19||x.hour==23||x.hour==27)
           {
               rowData[6]=3;
           }
           if(x.hour==4||x.hour==8||x.hour==12||x.hour==16||x.hour==20||x.hour==24||x.hour==28)
           {
              rowData[6]=4;          
             }      
     
            //rowData[6] = x.hour;
            rowData[7] = x.get_email();         
            rowData[8] = x.payment_type;
              
            rowData[9] =x.get_evnumber();
            /*  rowData[0] = client.clients.get(i).get_id();
            rowData[1] = c.clients.get(i).get_fname();
            rowData[2] = c.clients.get(i).get_lname();                  
            rowData[3] = c.clients.get(i).get_age();
            rowData[4] = c.clients.get(i).drug;  
            rowData[5] = c.clients.get(i).day;
            rowData[6] = c.clients.get(i).hour;
            rowData[7] = c.clients.get(i).get_email();*/
            model.addRow(rowData);
            
        }
        }catch(Exception e){
             JOptionPane.showMessageDialog(null,e+" in list");
        }

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "First name", "Last name", "Age", "drug", "day", "hour", "Email", "payment type", "evaluation"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, false, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
